# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\TOEL\Documents\Qtdesign\main_GUI\test001\payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_payment(object):
    def setupUi(self, payment):
        payment.setObjectName("payment")
        payment.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(payment)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.total_label2 = QtWidgets.QLabel(self.frame_2)
        self.total_label2.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.total_label2.setFont(font)
        self.total_label2.setObjectName("total_label2")
        self.horizontalLayout_3.addWidget(self.total_label2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(700, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\TOEL\\Documents\\Qtdesign\\main_GUI\\test001\\../../../Downloads/386468518_1090488795444867_7970713359013179603_n.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        payment.setCentralWidget(self.centralwidget)

        self.retranslateUi(payment)
        QtCore.QMetaObject.connectSlotsByName(payment)

    def retranslateUi(self, payment):
        _translate = QtCore.QCoreApplication.translate
        payment.setWindowTitle(_translate("payment", "MainWindow"))
        self.total_label2.setText(_translate("payment", "Total Price :"))
